### PR TITLE
Required label

### PR DESCRIPTION
**Pull request by Raruto**
Related to https://github.com/afragen/wp-dependency-installer/pull/37, improves distinctiveness and **comprehensibility of the label** (changed from "Plugin Dependency" to "Required Plugin")

**Before:**

label-before

**After:**

label-after

### CODE REVIEW

**Comment by afragen** [comment]
I'm working for the next several days and then I'm off to WordCamp Phoenix. I'll try to review/comment before then. Thanks, this makes it much easier for me.

**Comment by Raruto** [comment]
> I'm working for the next several days and then I'm off to WordCamp Phoenix. I'll try to review/comment before then. Thanks, this makes it much easier for me.

Don't worry, I'm a little busy too.

**Comment by afragen** [comment]
I'm curious as to why the small-caps. It seems a bit jarring as there is no other location in the dashboard that uses this.

**Comment by Raruto** [comment]
> It seems a bit jarring as there is no other location in the dashboard that uses this.

The objective is precisely to _slightly_ **increase the distinguishably** from the other elements of the table (and without being too invasive).

As we have already said:

- bold test is used for active plugins
- regular text is used for inactive plugins
- blue text is used for action links
- colored text is used (sometimes) for pro links

This seems to me the only way to be functional ( not confusable ) and at the same time not to make everything look like a Christmas tree...

**Review by afragen — APPROVED** [review]

**Pull request merged**
