### PR TITLE
add ability to set a "direct" ZIP download link

### PR DESCRIPTION
**Pull request by paulgoodchild**
Heya Andy/Matt,

Just wanted to share this with you. It's a simple addition to your system, whereby it makes it trivial to apply a dependency using a URI directly without relying on any source control providers.  I chose the host type "direct", but if that's not the most apt, perhaps another could be used.

Cheers.
Paul.

### CODE REVIEW

**Comment by afragen** [comment]
This look very interesting. I should be able to review it this weekend.

**Comment by afragen** [comment]
@paulgoodchild why the changes to .gitignore? Those files/folders don’t exist in this project until you install with composer.

**Comment by paulgoodchild** [comment]
Ahh yea, I have that in nearly all my .gitignores... it's a bit like the ignore for ".idea" I guess - it doesn't play a role unless you're developing through a particular IDE.  Feel free to scrap the .gitignore changes I added, it's no biggy at all :)

Thanks in-advance for reviewing it.

**Comment by afragen** [comment]
Here's the cleaned up commit. bfe1ff525bdeb90a5956c586c06450a9f201a78b

**Comment by paulgoodchild** [comment]
Brilliant stuff... thanks for taking the time to review and merge!

**Comment by afragen** [comment]
And thanks Paul for the PR. I should be releasing v1.4.0 later today. Update your composer.json accordingly. 😉

**Pull request merged**
