### PR TITLE
Added namespace and external class denotation

### PR DESCRIPTION
**Pull request by leemcd56**
In order to properly autoload through Composer, I had to add a namespace to `wp-dependency-installer.php`. Because`WPDI_Plugin_Installer_Skin` is extending class outside of its namespace, the class it is extending has to be denoted as such by adding a backslash before it.

Prior to change:
screen shot 2016-12-14 at 7 00 22 pm

After change:
screen shot 2016-12-14 at 6 59 44 pm

### CODE REVIEW

**Comment by afragen** [comment]
So I'm not sure what happened in your second commit, but it looks like a tab to space change.

**Comment by afragen** [comment]
Currently there are no namespaces. Class WP_Dependency_Installer and class WPDI_Plugin_Installer_Skin are not under a namespace. They are only under a conditional.

If you installed using Composer, the Composer autoload should load the class. Can you share the relevant code where you call the autoloader and the class?

**Comment by leemcd56** [comment]
Haha sorry about that, I work with spaces instead of tabs and my setup of Atom converts them automatically.

Sure! Using Gary Jones' [plugin boilerplate](https://github.com/GaryJones/plugin-boilerplate), in `plugin-slug.php`, adding `WP_Dependency_Installer::instance()->run( __DIR__ );` below the autoloader throws the aforementioned error:

```php
// Load Composer autoloader.
if ( file_exists( __DIR__ . '/vendor/autoload.php' ) ) {
    require_once __DIR__ . '/vendor/autoload.php';
}

// Load dependency installer
WP_Dependency_Installer::instance()->run( __DIR__ );

// Initialize the plugin.
$config = ConfigFactory::create( __DIR__ . '/config/defaults.php' );
Plugin::get_instance( $config->getSubConfig( 'Gamajo\PluginSlug' ) )->run();
```

**Comment by afragen** [comment]
Can you share the PHP error without the blackout? What is on line 45?

**Comment by afragen** [comment]
From the error it looks like you've created a namespace `Boone\WordPress\WP_Dependency_Installer` where it should only be `WP_Dependency_Installer`

**Comment by afragen** [comment]
Is `plugin-slug.php` namespaced with `Boone\WordPress`? If so, you will need to load the installer using `\WP_Dependency_Installer::instance()->run( __DIR__ );`

**Comment by leemcd56** [comment]
How hypocritical of me; you are certainly correct. My apologies for the trouble.

**Comment by afragen** [comment]
No worries. Glad it's working. I really did test it. 😝

**Comment by afragen** [comment]
Sometimes the smallest things are the hardest to see.

**Comment by leemcd56** [comment]
Agreed! I have been binge coding so I couldn't see what I had been doing wrong.

**Comment by afragen** [comment]
I hope the framework works well for your project.

**Pull request closed without merging**
